version: "3"

services:
  shlink:
    image: shlinkio/shlink:stable
    restart: always
    environment:
      - TZ="Europe/Zurich"
      - DEFAULT_DOMAIN=l.robn.ch
      - IS_HTTPS_ENABLED=true
      - GEOLITE_LICENSE_KEY=KEY
      - DB_DRIVER=maria
      - DB_USER=shlink
      - DB_NAME=shlink
      - DB_PASSWORD=PASSWORD
      - DB_HOST=database
    depends_on:
      - database
    ports:
      - 10.10.10.10:10030:8080

  database:
    image: mariadb:latest
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=PASSWORD
      - MARIADB_DATABASE=shlink
      - MARIADB_USER=shlink
      - MARIADB_PASSWORD=PASSWORD
    volumes:
      - /var/lib/docker/volumes/shlink/db_data:/var/lib/mysql/

  shlink-web-client:
    image: shlinkio/shlink-web-client
    ports:
      - 10.10.10.10:10031:80
