version: "3.0"
services:
  little-link:
    image: ghcr.io/techno-tim/littlelink-server:latest
    container_name: littlelink-server
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - META_TITLE=Robin Schulz  
      - LANG=de
      - META_INDEX_STATUS=all
      - THEME=Dark
      - NAME=Robin Schulz
      - GITHUB=https://robn.ch/github
      - INSTAGRAM=https://robn.ch/instagram
      - YOUTUBE=https://robn.ch/youtube
      - FACEBOOK=https://robn.ch/facebook
      - LINKED_IN=https://robn.ch/linkedin
      - DOCKERHUB=https://robn.ch/docker
      - PRINTABLES=https://robn.ch/printables
      - PAYPAL=https://robn.ch/paypal
      - BUTTON_TARGET=_blank
      - CUSTOM_BUTTON_TEXT=PDF Tools
      - CUSTOM_BUTTON_URL=https://robn.ch/pdf
      - CUSTOM_BUTTON_COLOR=#eb4034
      - CUSTOM_BUTTON_TEXT_COLOR=#ffffff
      - CUSTOM_BUTTON_NAME=PDF Tools
      - SKIP_HEALTH_CHECK_LOGS=true
    ports:
      - 10016:3000
    restart: always
    security_opt:
      - no-new-privileges:true
