version: "3.0"
services:
  little-link:
    image: ghcr.io/techno-tim/littlelink-server:latest
    # dockerhub is also supported timothystewart6/littlelink-server
    #image: timothystewart6/littlelink-server:latest
    container_name: littlelink-server
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - META_TITLE=Robin Schulz
      - META_AUTHOR=Robin Schulz
      - META_KEYWORDS=Smarthome, Electronic Engineering, IT-specialist, 3D-Printing      
      - LANG=de
      - META_INDEX_STATUS=all
      - THEME=Dark
      - FAVICON_URL=https://.jpg
      - AVATAR_URL=https://.jpg
      - AVATAR_2X_URL=https://.jpg
      - AVATAR_ALT=
      - NAME=Robin Schulz
      - BIO=
      - FOOTER=© Robin Schulz 2024
      - GITHUB=https://robn.ch/github
      - INSTAGRAM=https://robn.ch/instagram
      - YOUTUBE=https://robn.ch/youtube
      - FACEBOOK=https://robn.ch/facebook
      - LINKED_IN=https://robn.ch/linkedin
      - DOCKERHUB=https://robn.ch/docker
      - PRINTABLES=https://robn.ch/printables
      - PAYPAL=https://robn.ch/paypal
      - CUSTOM_BUTTON_TEXT=PDF Tools,Flow Chat,Bitwarden
      - CUSTOM_BUTTON_URL=https://robn.ch/pdftools,https://robn.ch/draw,https://robn.ch/bitwarden
      - CUSTOM_BUTTON_COLOR=#eb4034,#eb4034,#eb4034
      - CUSTOM_BUTTON_TEXT_COLOR=#ffffff,#ffffff,#ffffff
      - CUSTOM_BUTTON_NAME=PDF Tools,Flow Chart Maker,Bitwarden    
    ports:
      - 10016:3000
    restart: always
    security_opt:
      - no-new-privileges:true
