version: "3.3"

services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - network
    restart: always
networks:
  network:
    external: true
