version: "3.3"

services:
  traefik:
    image: "traefik:v3.3"
    container_name: "traefik-prod-01"
    networks:
      - web

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/usr/docker/volumes/traefik/config/traefik.yaml:/etc/traefik/traefik.yaml:ro"
      - "/usr/docker/volumes/traefik/cert:/etc/cert:ro"
      - "/usr/docker/volumes/traefik/letsencrypt:/letsencrypt"

networks:
  web:
    external: true